//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProjectBookkeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeesalary
    {
        public int id { get; set; }
        public Nullable<int> employee { get; set; }
        public Nullable<int> hourlyrate { get; set; }
        public Nullable<int> overwork { get; set; }
        public Nullable<int> sickdays { get; set; }
        public Nullable<int> bonus { get; set; }
    }
}
