//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProjectBookkeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeesalary
    {
        public int id { get; set; }
        public int employee { get; set; }
        public bool overwork { get; set; }
        public bool sickdays { get; set; }
        public bool bonus { get; set; }
        public int overall { get; set; }
        public int hourspermonth { get; set; }
    }
}
