//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProjectBookkeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaryfund
    {
        public int id { get; set; }
        public int worktime { get; set; }
        public int overwork { get; set; }
        public int sickdays { get; set; }
        public int totalsum { get; set; }
        public System.DateTime formationdate { get; set; }
    }
}
