//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProjectBookkeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class scholarshipfund
    {
        public int id { get; set; }
        public System.DateTime formationdate { get; set; }
        public int scholarshipsocial { get; set; }
        public int scholarshipgreat { get; set; }
        public int scholarshipgreatperfect { get; set; }
        public int scholarshipperfect { get; set; }
        public int basescholarship { get; set; }
        public int totalsum { get; set; }
    }
}
