//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProjectBookkeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentscholarship
    {
        public int id { get; set; }
        public int student { get; set; }
        public int grades { get; set; }
        public int scholarshiptype { get; set; }
        public bool ifsocial { get; set; }
        public bool ifsocialhelp { get; set; }
    }
}
