//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProjectBookkeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public int id { get; set; }
        public string lastname { get; set; }
        public string username { get; set; }
        public string patronymic { get; set; }
        public int userroleid { get; set; }
    
        public virtual userrole userrole { get; set; }
    }
}
